Repository MicrosoftStudentChapter/makeathon6-website, pull requests merged in 2024-02, with the labels that each got.

#71 Hamburgers changes made logo added
  app/page.js
  app/page.module.css
  components/Hamburger/Hamburger.js
  components/Hamburger/Hamburger.module.css
  components/animation/animation.module.css
  components/button/button.module.css
Labels: Requested changes

#73 Team component
  app/about/about.module.css
  app/about/components/Faq.jsx
  app/about/page.js
  app/app.js
  app/layout.js
  app/page.js
  app/page.module.css
  app/sponsors/page.js
  app/timeline/page.js
  app/tracks/page.js
  app/usePathnameProvider.js
  components/devfolioButton/devfolio.js
  components/devfolioButton/devfolio.module.css
  components/team/chulo.module.css
  components/team/data.json
  components/team/shakle/shakle.js
  components/team/shakle/shakle.module.css
  components/team/team.js
  next.config.js
  package-lock.json
  package.json
Labels: Under Progress

#74 Loader
  app/page.js
  components/Hamburger/Hamburger.module.css
  components/Loader/Crown.css
  components/Loader/Crown.jsx
  components/countdown/Countdown.css
  components/countdown/Countdown.jsx
  package.json
  public/fonts/helvetiker_regular.typeface.json
  public/ironCrown-transformed.glb
  public/loader/crown.glb
Labels: done
